# -*- coding: utf-8 -*-
"""xebiaHT1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwPv7EAhiFFy-gEenKD0_qFhVfkyAADd
"""

!pip install pandas numpy matplotlib seaborn scikit-learn statsmodels joblib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from statsmodels.tsa.arima.model import ARIMA

import pandas as pd
import numpy as np

np.random.seed(42)

months = pd.date_range(
    start='2022-01-01',
    periods=36,
    freq='M'
)

compute = np.random.randint(10000,20000,36)

storage = np.random.randint(3000,7000,36)

network = np.random.randint(50,150,36)

carbon = (
    compute*0.15 +
    storage*0.08 +
    network*3 +
    np.random.normal(0,50,36)
)

df = pd.DataFrame({
    'Month':months,
    'Compute_Hours':compute,
    'Storage_GB':storage,
    'Network_TB':network,
    'Carbon_Emission':carbon
})

df.head()
df.to_csv("cloud_carbon_emissions.csv", index=False)

df.info()

files.download("cloud_carbon_emissions.csv")

df.isnull().sum()

plt.figure(figsize=(10,5))

plt.plot(
    df['Month'],
    df['Carbon_Emission']
)

plt.title("Historical Carbon Emission Trend")
plt.show()

X = df[
[
'Compute_Hours',
'Storage_GB',
'Network_TB'
]
]

y = df['Carbon_Emission']

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

# Save training features
X_train.to_csv("X_train.csv", index=False)

# Save testing features
X_test.to_csv("X_test.csv", index=False)

# Save training target
y_train.to_csv("y_train.csv", index=False)

# Save testing target
y_test.to_csv("y_test.csv", index=False)

from google.colab import files

files.download("X_train.csv")
files.download("X_test.csv")
files.download("y_train.csv")
files.download("y_test.csv")

reg_model = LinearRegression()

reg_model.fit(
    X_train,
    y_train
)

print("Training Completed")

reg_predictions = reg_model.predict(
    X_test
)

reg_predictions

mae = mean_absolute_error(
    y_test,
    reg_predictions
)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        reg_predictions
    )
)

r2 = r2_score(
    y_test,
    reg_predictions
)

print("MAE =",mae)
print("RMSE =",rmse)
print("R2 =",r2)

ts = df['Carbon_Emission']

arima_model = ARIMA(
    ts,
    order=(5,1,0)
)

arima_fit = arima_model.fit()

print("ARIMA Model Trained")

forecast = arima_fit.forecast(
    steps=3
)

forecast

future_months = pd.date_range(
    start=df['Month'].iloc[-1],
    periods=4,
    freq='M'
)[1:]

future_months

plt.figure(figsize=(10,5))

plt.plot(
    df['Month'],
    df['Carbon_Emission'],
    label='Historical'
)

plt.plot(
    future_months,
    forecast,
    label='Forecast'
)

plt.legend()

plt.title(
    "Carbon Footprint Forecast"
)

plt.show()

df.to_csv(
    "xebia_carbon_dataset.csv",
    index=False
)

print("Dataset Saved")

from google.colab import files

files.download(
    "xebia_carbon_dataset.csv"
)